import { FullPageLoader } from 'Components/FullPageLoader'
import { Layout } from 'Components/layout'
import initAuth from 'Config/firebase/auth/utils/init-auth'
import type { NextPage } from 'next'
import Head from 'next/head'
import { AuthAction, useAuthUser, withAuthUser } from 'next-firebase-auth'
import styles from 'Styles/Home.module.css'

initAuth()

const Home: NextPage = () => {
  const AuthUser = useAuthUser()

  return (
    <Layout
      authLoading={!AuthUser.clientInitialized}
      email={AuthUser.email}
      signOut={AuthUser.signOut}
    >
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>
          <p>Your email is {AuthUser.email ? AuthUser.email : 'unknown'}.</p>
        </div>

        <ul>
          <li>
            if user is authenticated, he should <em>not</em> see this page.
          </li>
          <li>
            If you hard reload the page, a full page loading spinner should
            appear without flush.
          </li>
          <li>
            After loading is completed, page content should show up without
            flush.
          </li>
        </ul>

        <hr />

        <h1>
          I am{' '}
          <span style={{ color: 'red' }}>
            not authenticated: {(!AuthUser.email).toString()}
          </span>
        </h1>
      </div>
    </Layout>
  )
}

export default withAuthUser({
  whenUnauthedBeforeInit: AuthAction.SHOW_LOADER,
  LoaderComponent: FullPageLoader,
  whenAuthed: AuthAction.REDIRECT_TO_APP,
  appPageURL: '/authenticated',
})(Home)
